services:
  auth-service:
    image: auth-service:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: auth-service-dev
    env_file:
      - .env.${NODE_ENV}
    ports:
      - ${PORT}:8080
    volumes:
      - .:/usr/src/app # this is binding
      - /usr/src/app/node_modules
    command: npm run dev

  database:
    image: postgres:17.6-alpine
    container_name: postgres-dev-auth-service
    restart: always
    env_file:
      - .env.${NODE_ENV}
    ports:
      - "${DB_PORT}:5432"
    volumes: 
      - db_data:/var/lib/postgresql/data   # this is mounting

volumes:
  db_data:
        
