version: "3"

services:
  auth-service:
    image: auth-service:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: auth-service-dev
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command : npm run dev
    env_file:
      - .env
