version: "3"

services:
  auth-service:
    image: auth-service:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: auth-service-dev
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app # this is binding
      - /usr/src/app/node_modules
    command: npm run dev
    env_file:
      - .env.dev

  database:
    image: postgres:17.6-alpine
    container_name: postgres-dev-auth-service
    restart: always
    ports:
      - 5432:5432
    volumes: 
      - db_data:/var/lib/postgresql/data   # this is mounting
    env_file:
      - .env.dev

volumes:
  db_data:
        
